# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: yaml_to_json
        env:
          TRANSIFEX_TOKEN: ${{ secrets.REPORTIT_TRANSIFEX_TOKEN }}
        run: |
          python tools/yaml_to_json.py local
      - name: git identity
        run: |
          git config user.email "adam.kariv@gmail.com"
          git config user.name "Adam Kariv"
      - name: deploy
        run: |
          git checkout -b __deploy
          find src -name script.json | xargs git add
          find src -name \*.datapackage.tx.json | xargs git add
          git status
          git commit -m "Auto update of json sources"
          git push -v origin __deploy:master

